/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.capapresentacionbanco;

import BO.ClienteBO;
import Configuracion.DependencyInjector;
import DTO.ClienteDTO;
import Exception.NegocioException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

/**
 *
 * @author katia
 */
public class PantallaInicio extends javax.swing.JFrame {
    private ClienteBO clienteBO;
    private JLabel tituloLbl, idLbl, contraseñaLbl, mensajeLbl;
    private JTextField idTxtField;
    private JPasswordField contraseñaTxtField;
    private JButton btnIniciarSesion, btnRegistrarCliente, btnRetiroSinCuenta;


    /**
     * Creates new form PantallaInicio
     */
    public PantallaInicio() {
        this.clienteBO = DependencyInjector.getClienteBO();
        configurarVentana();
        initComponents2();
    }

    private void configurarVentana() {
        setTitle("Inicio - XimBank");
        setSize(1024, 768);
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    
    private void autenticarCliente() {
        try {
            int id = Integer.parseInt(idTxtField.getText().trim());
            String contra = new String(contraseñaTxtField.getPassword());

            ClienteDTO cliente = clienteBO.autenticarCliente(id, contra);
            mensajeLbl.setForeground(new Color(0, 128, 0));
            mensajeLbl.setText("Bienvenido, " + cliente.getNombre());
            
            DatosCliente pantallaDatos = new DatosCliente();
            pantallaDatos.mostrarConCliente(cliente.getIdCliente());
            pantallaDatos.setVisible(true);
            
            this.dispose();

        } catch (NumberFormatException e) {
            mensajeLbl.setForeground(Color.RED);
            mensajeLbl.setText("El ID debe ser numérico.");
        } catch (NegocioException e) {
            mensajeLbl.setForeground(Color.RED);
            mensajeLbl.setText(e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void initComponents2() {
        tituloLbl = new JLabel("XimBank");
        tituloLbl.setFont(new Font("Segoe UI Black", Font.BOLD, 48));
        tituloLbl.setAlignmentX(Component.CENTER_ALIGNMENT);

        idLbl = new JLabel("ID:");
        idLbl.setFont(new Font("Segoe UI", Font.PLAIN, 18));

        idTxtField = new JTextField(15);
        idTxtField.setFont(new Font("Segoe UI", Font.PLAIN, 16));

        contraseñaLbl = new JLabel("Contraseña:");
        contraseñaLbl.setFont(new Font("Segoe UI", Font.PLAIN, 18));

        contraseñaTxtField = new JPasswordField(15);
        contraseñaTxtField.setFont(new Font("Segoe UI", Font.PLAIN, 16));

        mensajeLbl = new JLabel(" ");
        mensajeLbl.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        mensajeLbl.setForeground(Color.RED);
        mensajeLbl.setHorizontalAlignment(SwingConstants.CENTER);

        btnIniciarSesion = new JButton("Iniciar sesión");
        btnRegistrarCliente = new JButton("Registrar cliente");
        btnRetiroSinCuenta = new JButton("Retirar sin cuenta");

        Dimension btnSize = new Dimension(250, 40);
        for (JButton btn : new JButton[]{btnIniciarSesion, btnRegistrarCliente, btnRetiroSinCuenta}) {
            btn.setPreferredSize(btnSize);
            btn.setMaximumSize(btnSize);
            btn.setAlignmentX(Component.CENTER_ALIGNMENT);
        }

        btnIniciarSesion.addActionListener(e -> autenticarCliente());
        btnRegistrarCliente.addActionListener(e -> {
            PantallaRegistroCliente pantalla = new PantallaRegistroCliente();
            pantalla.setVisible(true);
            this.dispose();
        });
        
        btnRetiroSinCuenta.addActionListener(e -> {
            PantallaRealizarRetiro pantalla = new PantallaRealizarRetiro();
            pantalla.setVisible(true);
            this.dispose(); 
        });


        // Panel de campos
        JPanel panelCampos = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.anchor = GridBagConstraints.LINE_END;

        gbc.gridx = 0;
        gbc.gridy = 0;
        panelCampos.add(idLbl, gbc);

        gbc.gridy = 1;
        panelCampos.add(contraseñaLbl, gbc);

        gbc.anchor = GridBagConstraints.LINE_START;
        gbc.gridx = 1;
        gbc.gridy = 0;
        panelCampos.add(idTxtField, gbc);

        gbc.gridy = 1;
        panelCampos.add(contraseñaTxtField, gbc);

        // Panel de botones
        JPanel panelBotones = new JPanel();
        panelBotones.setLayout(new BoxLayout(panelBotones, BoxLayout.Y_AXIS));
        panelBotones.add(Box.createVerticalStrut(20));
        panelBotones.add(btnIniciarSesion);
        panelBotones.add(Box.createVerticalStrut(10));
        panelBotones.add(btnRegistrarCliente);
        panelBotones.add(Box.createVerticalStrut(10));
        panelBotones.add(btnRetiroSinCuenta);

        // Panel central
        JPanel centro = new JPanel();
        centro.setLayout(new BoxLayout(centro, BoxLayout.Y_AXIS));
        centro.setAlignmentX(Component.CENTER_ALIGNMENT);
        centro.add(tituloLbl);
        centro.add(Box.createVerticalStrut(30));
        centro.add(panelCampos);
        centro.add(Box.createVerticalStrut(20));
        centro.add(mensajeLbl);
        centro.add(Box.createVerticalStrut(20));
        centro.add(panelBotones);

        getContentPane().setLayout(new GridBagLayout());
        getContentPane().add(centro);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PantallaInicio().setVisible(true);
//            }
//        });
        SwingUtilities.invokeLater(() -> new PantallaInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
