/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.capapresentacionbanco;

import BO.ClienteBO;
import Configuracion.DependencyInjector;
import DTO.ClienteDTO;
import Exception.NegocioException;
import com.github.lgooddatepicker.components.DatePicker;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

/**
 *
 * @author katia
 */
public class PantallaRegistroCliente extends javax.swing.JFrame {

    private final ClienteBO clienteBO;

    private JTextField nombreField, paternoField, maternoField, domicilioField;
    private DatePicker fechaNacimientoPicker;
    private JPasswordField contraseñaField;
    private JLabel mensajeLbl;
    
    /**
     * Creates new form PantallaRegistroCliente
     */
    public PantallaRegistroCliente() {
        this.clienteBO = DependencyInjector.getClienteBO();
        initComponents2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private void registrarCliente() {
        try {
            ClienteDTO dto = new ClienteDTO();
            dto.setNombre(nombreField.getText().trim());
            dto.setApellidoPaterno(paternoField.getText().trim());
            dto.setApellidoMaterno(maternoField.getText().trim());
            dto.setDomicilio(domicilioField.getText().trim());
            dto.setFechaNacimiento(fechaNacimientoPicker.getDate());

            String contra = new String(contraseñaField.getPassword());

            int idGenerado = clienteBO.registrarCliente(dto, contra);

            
            mensajeLbl.setForeground(new Color(0, 128, 0));
            mensajeLbl.setText("Cliente registrado correctamente. ID: " + idGenerado );
            limpiarCampos();
            

        } catch (NegocioException e) {
            mensajeLbl.setForeground(Color.RED);
            mensajeLbl.setText(e.getMessage());
        } catch (Exception e) {
            mensajeLbl.setForeground(Color.RED);
            mensajeLbl.setText("Campos inválidos. Revisa tus datos.");
        }
    }
    
    private void limpiarCampos() {
        nombreField.setText("");
        paternoField.setText("");
        maternoField.setText("");
        domicilioField.setText("");
        contraseñaField.setText("");
        fechaNacimientoPicker.clear();
    }
    
    private void initComponents2() {
        setTitle("Registro de Cliente - XimBank");
        setSize(1024, 768);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);

        JLabel tituloLbl = new JLabel("Registrar Cliente");
        tituloLbl.setFont(new Font("Segoe UI Black", Font.BOLD, 36));
        tituloLbl.setHorizontalAlignment(SwingConstants.CENTER);

        mensajeLbl = new JLabel(" ");
        mensajeLbl.setHorizontalAlignment(SwingConstants.CENTER);

        nombreField = new JTextField();
        paternoField = new JTextField();
        maternoField = new JTextField();
        domicilioField = new JTextField();
        contraseñaField = new JPasswordField();
        fechaNacimientoPicker = new DatePicker();

        JButton btnRegistrar = new JButton("Registrar");
        JButton btnAtras = new JButton("Atrás");

        btnRegistrar.addActionListener(e -> registrarCliente());
        btnAtras.addActionListener(e -> {
            new PantallaInicio().setVisible(true);
            dispose();
        });

        JPanel formPanel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;

        int y = 0;

        gbc.gridx = 0; gbc.gridy = y;
        formPanel.add(new JLabel("Nombre:"), gbc);
        gbc.gridx = 1;
        formPanel.add(nombreField, gbc);

        y++;
        gbc.gridx = 0; gbc.gridy = y;
        formPanel.add(new JLabel("Apellido paterno:"), gbc);
        gbc.gridx = 1;
        formPanel.add(paternoField, gbc);

        y++;
        gbc.gridx = 0; gbc.gridy = y;
        formPanel.add(new JLabel("Apellido materno:"), gbc);
        gbc.gridx = 1;
        formPanel.add(maternoField, gbc);

        y++;
        gbc.gridx = 0; gbc.gridy = y;
        formPanel.add(new JLabel("Domicilio:"), gbc);
        gbc.gridx = 1;
        formPanel.add(domicilioField, gbc);

        y++;
        gbc.gridx = 0; gbc.gridy = y;
        formPanel.add(new JLabel("Fecha de nacimiento:"), gbc);
        gbc.gridx = 1;
        formPanel.add(fechaNacimientoPicker, gbc);

        y++;
        gbc.gridx = 0; gbc.gridy = y;
        formPanel.add(new JLabel("Contraseña:"), gbc);
        gbc.gridx = 1;
        formPanel.add(contraseñaField, gbc);

        y++;
        gbc.gridx = 0; gbc.gridy = y; gbc.gridwidth = 2;
        formPanel.add(mensajeLbl, gbc);

        y++;
        JPanel botones = new JPanel();
        botones.add(btnRegistrar);
        botones.add(btnAtras);
        gbc.gridy = y;
        formPanel.add(botones, gbc);

        // Centrado
        setLayout(new BorderLayout());
        add(tituloLbl, BorderLayout.NORTH);
        add(formPanel, BorderLayout.CENTER);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
